name: Build, test and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: mbstring, bcmath, sqlite3, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Create database
        run: touch ./database/database.sqlite

      - name: Copy .env
        run: cp .env.test .env

      - name: Generate key
        run: php artisan key:generate

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run migrations
        run: php artisan migrate

      # - name: Test PHPStan
      #   run: ./vendor/bin/phpstan analyse

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit

      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@v1.1.0
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       cd ${{ secrets.APP_PATH }}
      #       ./build.sh
